spring:
  application:
    name: incident-management-system
  
  datasource:
    url: jdbc:h2:mem:incidentdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: INFO
    com.incidentmanagement: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  security:
    jwt:
      secret: ${JWT_SECRET:verySecretKeyThatShouldBeChangedInProduction}
      expiration: 86400000 # 24 hours in milliseconds
  monitoring:
    metrics-collection-interval: 60000 # 1 minute in milliseconds